import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const mdRoot = path.join(repoRoot, 'public', 'md-files');
const outFile = path.join(repoRoot, 'src', 'content', 'contentIndex.generated.js');

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const results = [];

  for (const ent of entries) {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      results.push(...walk(abs));
    } else if (ent.isFile() && ent.name.toLowerCase().endsWith('.md')) {
      results.push(abs);
    }
  }

  return results;
}

function slugify(parts) {
  return parts
    .join('-')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .replace(/-+/g, '-');
}

function extractTitle(md, fallbackName) {
  const lines = md.split(/\r?\n/);
  for (const line of lines) {
    const m = line.match(/^#\s+(.+)\s*$/);
    if (m) return m[1].trim();
  }
  return fallbackName;
}

function categoryFromRel(relPath) {
  const parts = relPath.split('/');
  if (parts.length <= 1) return 'General';
  return parts[0];
}

function posixRel(p) {
  return p.split(path.sep).join('/');
}

if (!fs.existsSync(mdRoot)) {
  console.error(`Missing folder: ${mdRoot}`);
  process.exit(1);
}

const filesAbs = walk(mdRoot);
filesAbs.sort((a, b) => a.localeCompare(b));

const items = [];
for (const abs of filesAbs) {
  const relToMdRoot = posixRel(path.relative(mdRoot, abs));
  const md = fs.readFileSync(abs, 'utf8');
  const baseName = path.basename(relToMdRoot, path.extname(relToMdRoot));

  // README.md at root is always the "home" page
  const isRootReadme = relToMdRoot.toLowerCase() === 'readme.md';
  const title = isRootReadme ? 'Home' : extractTitle(md, baseName);
  const partsForSlug = relToMdRoot.replace(/\.md$/i, '').split('/');
  const slug = isRootReadme ? 'home' : slugify(partsForSlug);

  items.push({
    title,
    slug,
    filePath: relToMdRoot,
    category: categoryFromRel(relToMdRoot),
  });
}

// Pin "home" (README.md) to the top
items.sort((a, b) => {
  if (a.slug === 'home') return -1;
  if (b.slug === 'home') return 1;
  return a.filePath.localeCompare(b.filePath);
});

const content = `// This file is auto-generated by scripts/buildContentIndex.mjs\n// Do not edit by hand.\n\nexport const contentIndex = ${JSON.stringify(items, null, 2)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');

console.log(`Wrote ${items.length} docs to ${path.relative(repoRoot, outFile)}`);
