// This file is auto-generated by scripts/buildRepoContent.mjs
// Do not edit by hand.

import type { Category, Post } from "../types/blog";

export const importedSeedVersion = "126f465b4cfaf361be357c89189b1fc404290480";

export const importedCategories: Category[] = [
  {
    "id": "general",
    "name": "General",
    "slug": "general",
    "order": 0
  }
];

export const importedPosts: Post[] = [
  {
    "id": "repo-readme",
    "title": "GSOC-Journey",
    "slug": "readme",
    "excerpt": "GSOC-Journey",
    "content": "# GSOC-Journey",
    "category": "general",
    "tags": [],
    "published": true,
    "createdAt": "2026-03-07T18:10:43.511Z",
    "updatedAt": "2026-03-07T18:10:43.511Z",
    "author": "Admin"
  }
];
