// This file is auto-generated by scripts/buildRepoContent.mjs
// Do not edit by hand.

import type { Category, Post } from "../types/blog";

export const importedSeedVersion = "80db934425fac1e612ad6de1f24cbdb60f6ed967";

export const importedCategories: Category[] = [
  {
    "id": "general",
    "name": "General",
    "slug": "general",
    "order": 0
  }
];

export const importedPosts: Post[] = [
  {
    "id": "repo-readme",
    "title": "GSOC-Journey",
    "slug": "readme",
    "excerpt": "GSOC-Journey",
    "content": "# GSOC-Journey",
    "category": "general",
    "tags": [],
    "published": true,
    "createdAt": "2026-03-25T16:45:22.362Z",
    "updatedAt": "2026-03-25T16:45:22.362Z",
    "author": "Admin"
  }
];
