// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseConfigError = isSupabaseConfigured
  ? null
  : 'Supabase environment variables are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY before deploying.';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createMissingConfigClient(): SupabaseClient<Database> {
  const proxyTarget = function missingSupabaseClient() {
    throw new Error(supabaseConfigError || 'Supabase is not configured.');
  };

  const handler: ProxyHandler<typeof proxyTarget> = {
    get() {
      return missingConfigProxy;
    },
    apply() {
      throw new Error(supabaseConfigError || 'Supabase is not configured.');
    },
    construct() {
      throw new Error(supabaseConfigError || 'Supabase is not configured.');
    },
  };

  const missingConfigProxy = new Proxy(proxyTarget, handler);
  return missingConfigProxy as unknown as SupabaseClient<Database>;
}

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMissingConfigClient();